spring:
  config:
    activate:
      on-profile: local

  # 로컬 개발용 Database 설정 (평문 입력)
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    # 로컬 테스트 시에는 운영 DB와 동일한 정보를 사용 (필요 시 로컬 DB로 변경 가능)
    url: jdbc:mariadb://pentiumman.synology.me:3306/neverlose?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: neverlose
    password: Skrkwk11##

  jpa:
    hibernate:
      ddl-auto: update

# 파일 저장 설정 (로컬 개발용 경로)
file:
  upload-dir: Z:\uploads
