spring:
  config:
    activate:
      on-profile: prod

  # 운영 서버용 Database 설정 (Docker 환경 변수로 주입)
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate # 운영 서버에서는 테이블 구조 자동 수정 방지

# 파일 저장 설정 (운영 서버/NAS 경로)
file:
  # 도커 컨테이너 내부 경로로 설정
  upload-dir: /app/uploads

server:
  # Nginx(HTTPS) -> Tomcat(HTTP) 시 프로토콜 인식을 위한 설정은 SwaggerConfig에서 GlobalOpenApiCustomizer로 처리함
  forward-headers-strategy: none
