

spring:
  application:
    name: bootSample
  
  # 기본 프로파일 설정 (로컬)
  profiles:
    active: local

  # 공통 JPA 설정
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

# 공통 Logging 설정
logging:
  level:
    kr.co.bootSample: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# SpringDoc (Swagger)
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operations-sorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true

# Server
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# 애플리케이션 공통 설정
app:
  file:
    paths:
      board: board
      editor: editor

# JWT 설정 (인증 만료 시간)
jwt:
  secret: ${JWT_SECRET:base64EncodedSecretKeyForBootSampleProjectThatIsLongEnough}
  expiration: 3600000 # 1시간 (60분 * 60초 * 1000ms)
